### ISSUE TITLE
please let it be runnable

### ISSUE THREAD

**Issue by wangzazao** [hoangtuanvu/Contract_Elements_Extraction#1]
hi,buddy,
Please provide the json files it needs. when i look into  create_dataset.py ,it tells the json files are to be loaded from your local computer rather than somewhere such as a web location.
Please let it be runnable for others !

**Comment by hoangtuanvu** [comment]
@wangzazao Sorry for late reply. You can download the sample files here:
https://drive.google.com/open?id=1vBdkTniG42zTCjLtKnr80-Ootk_bSPLa

After that, we should put these ones to the path: bert/contract for training and testing model.

**Comment by hoangtuanvu** [comment]
@wangzazao I will close this.
