### ISSUE TITLE
The code ignore GPU

### ISSUE THREAD

**Issue by wangzazao** [hoangtuanvu/Contract_Elements_Extraction#2]
hi,
buddy,when run it to train the model,the code ignore my gpu and use cpus instead,I am sure my GPU installation is right.
so,how to tweak the code  to use my gpu?

**Comment by hoangtuanvu** [comment]
@wangzazao Sorry for fixed code in line 19:
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

You could try to modify this.

**Comment by wangzazao** [comment]
tks，
I try to fixed it by using the right number to replace the '2'
but the code required such a  lot of gpu memory that my 2 gpu (8+8=16g) still can not satisfy it.
So,i have to turn back to my cpu
